export const sharedStyles = {
  main: {
    backgroundColor: "#f4f4f5",
    fontFamily: 'Inter, -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif',
    padding: "20px 0",
  },
  container: {
    backgroundColor: "#ffffff",
    margin: "0 auto",
    padding: "0",
    borderRadius: "24px",
    overflow: "hidden",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.05)",
    maxWidth: "600px",
  },
  headerAdmin: {
    backgroundColor: "#18181b",
    padding: "40px 20px",
    textAlign: "center" as const,
  },
  headerStorefront: {
    backgroundColor: "#dc2626",
    padding: "40px 20px",
    textAlign: "center" as const,
  },
  h1: {
    color: "#ffffff",
    fontSize: "32px",
    fontWeight: "900",
    margin: "0",
    letterSpacing: "-1px",
  },
  content: {
    padding: "40px 40px",
  },
  h2: {
    color: "#18181b",
    fontSize: "24px",
    fontWeight: "800",
    margin: "0 0 16px",
    letterSpacing: "-0.5px",
  },
  text: {
    color: "#3f3f46",
    fontSize: "16px",
    lineHeight: "26px",
    margin: "0 0 20px",
  },
  sectionAdmin: {
    padding: "24px",
    backgroundColor: "#f4f4f5",
    borderRadius: "16px",
    margin: "30px 0",
    border: "1px solid #e4e4e7", 
  },
  sectionStorefront: {
    padding: "24px",
    backgroundColor: "#fef2f2",
    borderRadius: "16px",
    margin: "30px 0",
    border: "1px solid #fecaca", 
  },
  strongAdmin: {
    color: "#18181b",
    fontWeight: "800",
    fontSize: "18px",
    margin: "0 0 16px",
  },
  strongStorefront: {
    color: "#dc2626",
    fontWeight: "800",
    fontSize: "18px",
    margin: "0 0 16px",
  },
  sectionHrAdmin: {
    borderColor: "#d4d4d8",
    margin: "12px 0 16px",
  },
  sectionHrStorefront: {
    borderColor: "#fca5a5",
    margin: "12px 0 16px",
  },
  textRow: {
    margin: "0 0 10px",
    fontSize: "15px",
    color: "#3f3f46",
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
  },
  label: {
    fontWeight: "600",
  },
  value: {
    fontWeight: "700",
    color: "#18181b",
    float: "right" as const,
  },
  valueTotalAdmin: {
    fontWeight: "700",
    color: "#2563eb",
    float: "right" as const,
    fontSize: "18px",
  },
  valueTotalStorefront: {
    fontWeight: "700",
    color: "#dc2626",
    float: "right" as const,
    fontSize: "18px",
  },
  valueDiscount: {
    fontWeight: "700",
    color: "#16a34a",
    float: "right" as const,
  },
  hr: {
    borderColor: "#e4e4e7",
    margin: "30px 0",
  },
  footer: {
    color: "#71717a",
    fontSize: "14px",
    lineHeight: "22px",
    textAlign: "center" as const,
  },
  button: {
    backgroundColor: "#dc2626",
    color: "#ffffff",
    padding: "16px 32px",
    borderRadius: "9999px",
    textDecoration: "none",
    display: "inline-block",
    fontWeight: "800",
    fontSize: "16px",
    letterSpacing: "0.5px",
  },
  buttonOutline: {
    backgroundColor: "transparent",
    color: "#18181b",
    border: "2px solid #18181b",
    padding: "16px 32px",
    borderRadius: "9999px",
    textDecoration: "none",
    display: "inline-block",
    fontWeight: "800",
    fontSize: "16px",
    letterSpacing: "0.5px",
  },
};
